/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoadmapsRouteImport } from './routes/roadmaps'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const RoadmapsRoute = RoadmapsRouteImport.update({
  id: '/roadmaps',
  path: '/roadmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/communities': typeof CommunitiesRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/forum': typeof ForumRoute
  '/mentors': typeof MentorsRoute
  '/roadmaps': typeof RoadmapsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/communities': typeof CommunitiesRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/forum': typeof ForumRoute
  '/mentors': typeof MentorsRoute
  '/roadmaps': typeof RoadmapsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/communities': typeof CommunitiesRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/forum': typeof ForumRoute
  '/mentors': typeof MentorsRoute
  '/roadmaps': typeof RoadmapsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/communities'
    | '/contact'
    | '/events'
    | '/forum'
    | '/mentors'
    | '/roadmaps'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/communities'
    | '/contact'
    | '/events'
    | '/forum'
    | '/mentors'
    | '/roadmaps'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/communities'
    | '/contact'
    | '/events'
    | '/forum'
    | '/mentors'
    | '/roadmaps'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommunitiesRoute: typeof CommunitiesRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  ForumRoute: typeof ForumRoute
  MentorsRoute: typeof MentorsRoute
  RoadmapsRoute: typeof RoadmapsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roadmaps': {
      id: '/roadmaps'
      path: '/roadmaps'
      fullPath: '/roadmaps'
      preLoaderRoute: typeof RoadmapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommunitiesRoute: CommunitiesRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  ForumRoute: ForumRoute,
  MentorsRoute: MentorsRoute,
  RoadmapsRoute: RoadmapsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
